// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func CreateCategory() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"mt-5 md:pl-20 xl:pl-72 2xl:pl-96 md:pr-20 xl:pr-72 2xl:pr-96\"><div><label for=\"categoryNam\" class=\"block text-sm font-medium text-gray-900\">Category Name </label> <input type=\"text\" id=\"categoryName\" placeholder=\"Enter Category name\" class=\"mt-1 w-full rounded-md border-gray-200 shadow-sm sm:text-sm\"></div><fieldset class=\"mt-2\"><legend class=\"sr-only\">Checkboxes</legend><div class=\"space-y-2\"><label for=\"Option1\" class=\"flex cursor-pointer items-start gap-4 rounded-lg border border-gray-200 p-4 transition hover:bg-gray-50 has-[:checked]:bg-blue-50\"><div class=\"flex items-center\">&#8203; <input type=\"checkbox\" class=\"size-4 rounded border-gray-300\" id=\"Option1\"></div><div><strong class=\"font-medium text-gray-900\">Sub Category</strong><p class=\"mt-1 text-pretty text-sm text-gray-700\">Select if the newly created category is a sub category to another.</p></div></label></div></fieldset><div class=\"mt-2\"><label for=\"HeadlineAct\" class=\"block text-sm font-medium text-gray-900\">Parent Category</label> <select name=\"HeadlineAct\" id=\"HeadlineAct\" class=\"mt-1.5 w-full rounded-lg border-gray-300 text-gray-700 sm:text-sm\"><option value=\"\">Please select one</option> <option value=\"JM\">John Mayer</option> <option value=\"SRV\">Stevie Ray Vaughn</option> <option value=\"JH\">Jimi Hendrix</option> <option value=\"BBK\">B.B King</option> <option value=\"AK\">Albert King</option> <option value=\"BG\">Buddy Guy</option> <option value=\"EC\">Eric Clapton</option></select></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
