services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air --build.cmd "go build -o build/backend cmd/main.go" --build.bin "build/backend"

  db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
