services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: .
    depends_on:
      - migrate
    volumes:
      - .:/usr/src/app
    command: air --build.cmd "go build -o build/backend cmd/main.go" --build.bin "build/backend"

  db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./internal/infrastructure/database/migrations:/migration
    command:
      [
        "-path",
        "./migration",
        "-database",
        "postgres://n1h41:n2ks9x64@db:5432/marketplace?sslmode=disable",
        "-verbose",
        "up",
      ]
volumes:
  postgres-db:
