CREATE TABLE category (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
  name VARCHAR(255) NOT NULL,
  is_sub_category BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
