CREATE TABLE product (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
  name VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL,
  stocks INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
